### ISSUE TITLE
Dependency Installation Error with memoria Leading to Failed Execution in better-bing-image-downloader 

### ISSUE THREAD

**Issue by lundeen-bryan** [KTS-o7/better_bing_image_downloader#10]
**Title**: Dependency Installation Error with `memoria` Leading to Failed Execution in `better-bing-image-downloader`

**Environment**:
- `better-bing-image-downloader` Version: 1.1.0
- Python Version: Tried on 3.9.5 and 3.11.8
- Operating System: Windows 11

**Description**:
The `better-bing-image-downloader` installs without issues, but upon execution, it fails with an error related to missing dependencies, specifically `memoria`. Following the error chain to install `memoria` leads to a deprecated dependency issue involving `sklearn`, which is now replaced by `scikit-learn`. Attempts to rectify this through environment variables and direct installation of `scikit-learn` were unsuccessful.

**Steps to Reproduce**:
1. Install `better-bing-image-downloader` version 1.1.0.
2. Run a script utilizing `better-bing-image-downloader`.
3. The execution prompts an installation of `memoria` due to a missing dependency.
4. Installing `memoria` leads to an error involving a deprecated package `sklearn`, suggesting the use of `scikit-learn` instead.

**Expected Behavior**:
`better-bing-image-downloader` should run without requiring the manual resolution of deprecated dependencies, particularly between `sklearn` and `scikit-learn`.

**Actual Behavior**:
The tool fails to run due to a cascade of dependency-related errors, starting with `memoria` and leading to issues with deprecated `sklearn` package installations.

**Impact**:
This issue blocks the usage of `better-bing-image-downloader`, as it can't execute its core functionality without resolving these dependency issues, impacting project progress where image downloading is required.

**Logs/Error Messages**:
For a detailed traceback and error messages, please refer to the initial queries in this ticket submission.

**Suggested Fix or Workaround**:
A review and update of the dependencies within `better-bing-image-downloader` and its related packages (`memoria`, and further dependencies therein) could potentially resolve this issue. Ensuring compatibility with `scikit-learn` instead of the deprecated `sklearn` package could be a critical part of the solution.

**Comment by KTS-o7** [comment]
Will do the necessary changes

**Comment by KTS-o7** [comment]
@lundeen-bryan  this project doesnt require memoria and currently isnt conflicting scikit-learn. Maybe if you provide error logs we can look into this further.

**Comment by lundeen-bryan** [comment]
No the error log said that it requires memoria. Most likely one of the dependencies requires it. 

I'm using Python 3.11 is that the same Python version you use? I'm guessing that something in your package is not compatible with my version of python so it tries to use memoria for backwards compatibility. 

However, the project I was working on I put on the back burner so I don't have the error logs directly. If everything is working when you run your package, maybe can you give me the requirements file and what version of Python you run in order to make your package work? I'll then duplicate your environment and Python version which should give me the same result you have.

**Comment by KTS-o7** [comment]
I Am using python 3.11.8 and `requirements.txt` is already present in the project.
You can check it out here - [requirements.txt](https://github.com/KTS-o7/better_bing_image_downloader/blob/main/requirements.txt)

**Comment by KTS-o7** [comment]
@lundeen-bryan  One workaround is to use this as a command line tool. You can run the following command
`python download.py -l 10 "image_query_name" -v`

**Comment by KTS-o7** [comment]
Since no reply was given. Issue is considered fixed.
