### ISSUE TITLE
Call back for progress

### ISSUE THREAD

**Issue by BubblyDevil** [KTS-o7/better_bing_image_downloader#13]
First of all thank you for your library. I am using it in a PyQT5 python application. Is  there any way to get the progress update to my calling function so that I can update the progress bar on my GUI

**Comment by BubblyDevil** [comment]
Normally I am importing your library and then issuing the download command. While in command line it shows the progress. I want to show this progress in my gui. Let say I am downloading 10 images of cats. So for every complete image downloaded my progress bar (the pyqtprogressbar on my gui) should move 10%.

**Comment by KTS-o7** [comment]
We currently dont have an API so far. Feel free to add it tho.
