### ISSUE TITLE
multidownloader example in readme is not working

### ISSUE THREAD

**Issue by guillaume-safi** [KTS-o7/better_bing_image_downloader#14]
I ran the following example:
```bash
python multidownloader.py "Cool Doggos" --engine "Google" --driver "chrome_headless" --max-number 50 --num-threads 10 --timeout 60 --output "./doggo_images" --safe-mode --proxy_http "192.168.0.2:8080" --type "photograph" --color "blue"
```

![image](https://github.com/KTS-o7/better_bing_image_downloader/assets/146853227/34889343-3fe8-4d85-9dbc-82fcd930ec66)

And it finds 0 images. 

I am on ubuntu 22.04, bing works. I think its something to do with Chrome.

**Comment by KTS-o7** [comment]
Yes indeed.
Google requires an API to scrape. Hence advised to use Mozilla Firefox.
Please check the docstrings to get the proper output.
